Repository MEME-UMC/MEME_iOS, pull requests merged in 2024-03, with the labels that each got.

#38 [Feat] 리뷰 리스트 API 연결
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Assets.xcassets/ModelReservation/img_zeroStar.imageset/Contents.json
  MEME/MEME/Assets.xcassets/ModelReservation/img_zeroStar.imageset/Group 1761 (1).png
  MEME/MEME/Assets.xcassets/ModelReservation/img_zeroStar.imageset/Group 1761 (2).png
  MEME/MEME/Assets.xcassets/ModelReservation/img_zeroStar.imageset/Group 1761.png
  MEME/MEME/Model/ModelHomeView/ModelHomeViewController.swift
  MEME/MEME/Model/ModelHomeView/SelectMakeupCardCell/SelectMakeupCardViewCell.swift
  MEME/MEME/Model/ModelManagementReservationsView/ModelManagementReservationsViewController.swift
  MEME/MEME/Model/ModelReservationDetailView/ModelReservationLastViewController.swift
  MEME/MEME/Model/ModelReservationView/ModelReservationSegmentedControl.swift
  MEME/MEME/Model/ModelReservationView/ModelReservationViewController.swift
  MEME/MEME/Model/ModelReservationView/ShowReviewView/ShowReviewTableViewCell.swift
  MEME/MEME/Model/ModelReservationView/ShowReviewView/ShowReviewView.swift
  MEME/MEME/Model/MyReview/MyReviewViewController.swift
  MEME/MEME/Network/API/PortfolioAPI.swift
  MEME/MEME/Network/API/ReviewAPI.swift
  MEME/MEME/Network/Manager/ReviewManager.swift
Labels: feature

#42 [Fix] ModelView 관련 사소한 수정
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Assets.xcassets/Color/SubRed.colorset/Contents.json
  MEME/MEME/Model/ModelHomeView/ModelHomeViewController.swift
  MEME/MEME/Model/ModelHomeView/ModelReservationCell/ModelReservationConfirmCell/ModelReservationConfirmViewCell.swift
  MEME/MEME/Model/ModelHomeView/SelectMakeupCardCell/SelectMakeupCardViewCell.swift
  MEME/MEME/Model/ModelHomeView/SelectMakeupCardCell/SelectMakeupCardViewCell.xib
  MEME/MEME/Model/ModelManagementReservationsView/ModelCancelReservationViewController.swift
  MEME/MEME/Model/ModelManagementReservationsView/ModelManagementReservationsViewController.swift
  MEME/MEME/Model/ModelReservationChartView/ModelReservationChartTableViewCell/ModelReservationChartTableViewCell.xib
  MEME/MEME/Model/ModelReservationDetailView/ModelReservationDetailViewController.swift
  MEME/MEME/Model/ModelReservationDetailView/ModelReservationLastViewController.swift
  MEME/MEME/Model/ModelReservationDetailView/ModelReservationLocationView/ModelReservationBothLocationView.swift
  MEME/MEME/Model/ModelReservationDetailView/ModelReservationLocationView/ModelReservationShopLocationView.swift
  MEME/MEME/Model/ModelReservationView/ModelReservationViewController.swift
  MEME/MEME/Model/ModelReservationView/ShowReviewView/ShowReviewTableViewCell.swift
  MEME/MEME/Model/ModelSearchView/ModelSearchResultViewController.swift
  MEME/MEME/Network/API/ReservationAPI.swift
  MEME/MEME/Network/Manager/ReservationManager.swift
  MEME/MEME/Network/Response/ReservationDTO.swift
  MEME/MEME/Network/Response/ReviewListDTO.swift
  MEME/MEME/Network/Response/SearchDTO.swift
Labels: fix

#46 [Fix] 폴더 정리 및 VC명 수정
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Core/TabBar/ArtistTabBarController.swift
  MEME/MEME/ManagementReservationsDateCollectionViewCell.swift
  MEME/MEME/ManagementReservationsViewController.swift
  MEME/MEME/Model/ModelHomeView/ModelHomeViewController.swift
Labels: duplicate, fix

#48 [ Move] 폴더 재배치 및 정리
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Artist/ReservationManagement/ManagementReservationsDateCollectionViewCell.swift
  MEME/MEME/Artist/ReservationManagement/ManagementReservationsViewController.swift
Labels: duplicate, fix

#52 [Fix] 폰트 사이즈 수정, 데이터 전달 누락 수정
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Model/ModelHomeView/ModelHomeViewController.swift
  MEME/MEME/Model/ModelManagementReservationsView/ModelCancelReservationViewController.swift
  MEME/MEME/Model/ModelReservationDetailView/ModelReservationDetailViewController.swift
  MEME/MEME/Model/ModelReservationDetailView/ModelReservationLastViewController.swift
Labels: fix

#53 [Feat] 아티스트, 포트폴리오 API 연결 및 UI 수정
  MEME/MEME/Artist/ArtistData.swift
  MEME/MEME/Artist/ArtistHome/ArtistHomeViewController.swift
  MEME/MEME/Artist/ArtistHome/ArtistHomeViewController.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistMakeupTagCollectionViewCell.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioCollectionViewCell.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioEditingViewController.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioEditingViewController.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioManageViewController.swift
  MEME/MEME/Artist/ArtistReservation/ArtistReservationStatusTableViewCell.swift
  MEME/MEME/Artist/ArtistReservation/ArtistReservationStatusTableViewCell.xib
  MEME/MEME/Artist/ArtistReservation/SingleArtistReservationManageViewController.swift
  MEME/MEME/Artist/ArtistReservation/SingleArtistReservationManageViewController.xib
  MEME/MEME/Artist/ReservationManagement/ManagementReservationsDateCollectionViewCell.swift
  MEME/MEME/Artist/ReservationManagement/ManagementReservationsViewController.swift
  MEME/MEME/Core/Artist/PortfolioCategories.swift
  MEME/MEME/Network/Manager/PortfolioManager.swift
  MEME/MEME/Network/Manager/ReservationManager.swift
  MEME/MEME/Network/Response/PortfolioDTO.swift
  MEME/MEME/Network/Response/ProfileDTO.swift
Labels: duplicate, feature, fix

#55 [Fix] 로그인 플로우 수정
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/AppDelegate.swift
  MEME/MEME/Core/RoleType.swift
  MEME/MEME/Core/TabBar/ArtistTabBarController.swift
  MEME/MEME/Core/TabBar/ModelTabBarController.swift
  MEME/MEME/Foundation/KeyChainManager.swift
  MEME/MEME/Foundation/KeyChainValue.swift
  MEME/MEME/Info.plist
  MEME/MEME/Login/Login/LoginViewController.swift
  MEME/MEME/Model/ModelManagementReservationsView/ModelCancelReservationViewController.swift
  MEME/MEME/Network/API/AuthAPI.swift
  MEME/MEME/Network/Manager/Auth/AuthManager.swift
  MEME/MEME/Network/Manager/Auth/BusinessIDVerificationManager.swift
  MEME/MEME/Network/Response/LoginDTO.swift
  MEME/MEME/SceneDelegate.swift
Labels: bug, fix

#62 [Fix] ModelCancelReservationViewController 주석 처리 제거, 모델 아이디 불러오는 코드 수정
  MEME/MEME/Model/ModelManagementReservationsView/ModelCancelReservationViewController.swift
  MEME/MEME/Model/ModelSearchView/ModelSearchViewController.swift
Labels: fix

#64 [Fix] artistID KeychainManager 사용 및 UI 수정
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Artist/ArtistData.swift
  MEME/MEME/Artist/ArtistHome/ArtistHomeViewController.swift
  MEME/MEME/Artist/ArtistHome/ArtistHomeViewController.xib
  MEME/MEME/Artist/ArtistMyPage/ArtistMyPageViewController.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioCollectionViewCell.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioCollectionViewCell.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioEditingViewController.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioManageViewController.swift
  MEME/MEME/Artist/ArtistReservation/ArtistReservationManageViewController.swift
  MEME/MEME/Artist/ArtistReservation/ArtistReservationManageViewController.xib
  MEME/MEME/Artist/ArtistReservation/ArtistReservationStatusTableViewCell.xib
  MEME/MEME/Artist/ArtistReservation/EntireArtistReservationManageViewController.swift
  MEME/MEME/Artist/ArtistReservation/EntireArtistReservationManageViewController.xib
  MEME/MEME/Artist/ArtistReservation/SingleArtistReservationManageViewController.swift
  MEME/MEME/Artist/ReservationManagement/ManagementReservationsViewController.swift
  MEME/MEME/Assets.xcassets/ModelHome/icon_location_disabled.imageset/Contents.json
  MEME/MEME/Assets.xcassets/ModelHome/icon_location_disabled.imageset/ic_map 1.svg
  MEME/MEME/Assets.xcassets/ModelHome/icon_location_disabled.imageset/ic_map 2.svg
  MEME/MEME/Assets.xcassets/ModelHome/icon_location_disabled.imageset/ic_map.svg
  MEME/MEME/Core/NavigationBarView.swift
  MEME/MEME/Core/NavigationBarView.xib
  MEME/MEME/Model/ModelHomeView/ModelReservationCell/ModelReservationConfirmCell/ModelReservationConfirmViewCell.swift
  MEME/MEME/Model/ModelReservationView/ModelReservationViewController.swift
  MEME/MEME/Model/ModelViewArtistProfileView/ModelViewArtistProfileViewController.swift
  MEME/MEME/Network/API/PortfolioAPI.swift
  MEME/MEME/Network/Manager/PortfolioManager.swift
  MEME/MEME/Network/Response/SearchDTO.swift
Labels: fix

#72 [ fix]문의하기 VC navigaionBar, TabBar hidden 처리수정
  MEME/MEME/Model/MyPage/AskViewController.swift
Labels: bug, fix
