Repository MEME-UMC/MEME_iOS, pull requests merged in 2024-04, with the labels that each got.

#78 [Feat] navigation Controller 커스텀
  MEME/MEME/Assets.xcassets/ic_back.imageset/Contents.json
  MEME/MEME/Assets.xcassets/ic_back.imageset/ic_back.svg
  MEME/MEME/Assets.xcassets/ic_back.imageset/ic_back@2x.png
  MEME/MEME/Assets.xcassets/ic_back.imageset/ic_back@3x.png
  MEME/MEME/Core/NavigationController.swift
Labels: feature

#79 [Fix] UI 색상 처리, 폴더 정리, 코드 컨벤션 적용
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Artist/ArtistHome/ArtistHomeView/ArtistHomeViewController.swift
  MEME/MEME/Artist/ArtistHome/ArtistHomeView/ArtistHomeViewController.xib
  MEME/MEME/Artist/ArtistInfo/ArtistInfoDetailView/ArtistInfoDetailViewController.swift
  MEME/MEME/Artist/ArtistInfo/ArtistInfoDetailView/ArtistInfoDetailViewController.xib
  MEME/MEME/Artist/ArtistInfo/ArtistInfoView/ArtistInfoViewController.swift
  MEME/MEME/Artist/ArtistInfo/ArtistInfoView/ArtistInfoViewController.xib
  MEME/MEME/Artist/ArtistLocation/ArtistLocationCollectionViewCell.swift
  MEME/MEME/Artist/ArtistLocation/ArtistLocationView/ArtistLocationViewController.swift
  MEME/MEME/Artist/ArtistLocation/ArtistLocationView/ArtistLocationViewController.xib
  MEME/MEME/Artist/ArtistMyPage/ArtistHeaderView/ArtistHeaderView.swift
  MEME/MEME/Artist/ArtistMyPage/ArtistMyPageView/ArtistMyPageViewController.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistMakeupTagCollectionViewCell/ArtistMakeupTagCollectionViewCell.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistMakeupTagCollectionViewCell/ArtistMakeupTagCollectionViewCell.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioCollectionViewCell/ArtistPortfolioCollectionViewCell.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioCollectionViewCell/ArtistPortfolioCollectionViewCell.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioEditingView/ArtistPortfolioEditingViewController.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioEditingView/ArtistPortfolioEditingViewController.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioManageView/ArtistPortfolioManageViewController.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioManageView/ArtistPortfolioManageViewController.xib
  MEME/MEME/Artist/ArtistReservation/ArtistReservationStatusTableViewCell/ArtistReservationStatusTableViewCell.swift
  MEME/MEME/Artist/ArtistReservation/ArtistReservationStatusTableViewCell/ArtistReservationStatusTableViewCell.xib
  MEME/MEME/Artist/ArtistReservation/SingleArtistReservationManageView/SingleArtistReservationManageViewController.swift
  MEME/MEME/Artist/ArtistReservation/SingleArtistReservationManageView/SingleArtistReservationManageViewController.xib
  MEME/MEME/Artist/ArtistTime/ArtistTimeCollectionViewCell.swift
  MEME/MEME/Artist/ArtistTime/ArtistTimeComplementaryView/ArtistTimeHeaderSupplementaryView.swift
  MEME/MEME/Artist/ManagementReservation/ ManagementReservationsView/ManagementReservationsViewController.swift
  MEME/MEME/Artist/ManagementReservation/ManagementReservationsDateCollectionViewCell.swift
  MEME/MEME/Artist/ProvisionView/ProvisionViewController.swift
Labels: fix, refactoring

#83 [Feat] Moya Wrapper 구현, async request 메서드 추가
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Network/Foundation/NetworkProvider.swift
  MEME/MEME/Network/Moya/Moya+Wrapping.swift
  MEME/MEME/Network/Moya/MoyaAsyncError.swift
  MEME/MEME/Network/Moya/MoyaAsyncRequest.swift
  MEME/MEME/Network/Moya/MoyaProvider+Async.swift
Labels: feature

#91 [Feat] UIViewController+rx 구현
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Core/UIViewController+Rx.swift
Labels: feature

#92 [Refactoring] 모델 회원 가입 MVVM으로 리팩토링
  MEME/MEME.xcodeproj/project.pbxproj
  MEME/MEME/Core/NavigationController.swift
  MEME/MEME/Core/UserDefaultManager.swift
  MEME/MEME/Login/Artist/BusinessRegstration/BusinessRegistrationViewController.swift
  MEME/MEME/Login/Common/Login/ViewModel/LoginViewModel.swift
  MEME/MEME/Login/Common/RegistrationCompletion/RegistrationCompletionViewController.swift
  MEME/MEME/Login/Common/RegistrationCompletion/RegistrationCompletionViewController.xib
  MEME/MEME/Login/Common/RegistrationCompletion/ViewModel/RegisterCompletionViewModel.swift
  MEME/MEME/Login/Common/SetProfile/SetProfileViewController.swift
  MEME/MEME/Login/Common/SetProfile/ViewModel/SetProfileViewModel.swift
  MEME/MEME/Login/Coordinator/ModelSignUpCoordinator.swift
  MEME/MEME/Login/Coordinator/SignUpCoordinator.swift
  MEME/MEME/Login/Model/Coordinator/SignUpCompletionCoordinator.swift
  MEME/MEME/Login/Model/SetDetailInfo/SetDetailInfoViewController.swift
  MEME/MEME/Login/Model/SetDetailInfo/SetDetailInfoViewController.xib
  MEME/MEME/Login/Model/SetDetailInfo/ViewModel/SetModelDetailInfoViewModel.swift
  MEME/MEME/Login/Model/SetDetailInfo/Views/SetModelDetailInfoViewController.swift
  MEME/MEME/Login/Model/SetDetailInfo/Views/SetModelDetailInfoViewController.xib
  MEME/MEME/Login/Model/SetDetailInfo/Views/SubViews/ModelDetailInfoCollectionViewCell.swift
  MEME/MEME/Login/Model/SetDetailInfo/Views/SubViews/ModelDetailInfoHeaderView.swift
  MEME/MEME/Network/API/AuthAPI.swift
  MEME/MEME/Network/Foundation/MEMEError.swift
  MEME/MEME/Network/Manager/Auth/AuthManager.swift
  MEME/MEME/extenstions/UICollectionView+.swift
  MEME/MEME/extenstions/UIView+.swift
Labels: refactoring

#94 [Refactor] 아티스트 네비게이션 바 변경 및 기타 UI 수정사항
  MEME/MEME.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MEME/MEME/Artist/ArtistHome/ArtistHomeView/ArtistHomeViewController.swift
  MEME/MEME/Artist/ArtistHome/ArtistHomeView/ArtistHomeViewController.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistMakeupTagCollectionViewCell/ArtistMakeupTagCollectionViewCell.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistMakeupTagCollectionViewCell/ArtistMakeupTagCollectionViewCell.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioCollectionViewCell/ArtistPortfolioCollectionViewCell.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioEditingView/ArtistPortfolioEditingViewController.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioEditingView/ArtistPortfolioEditingViewController.xib
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioManageView/ArtistPortfolioManageViewController.swift
  MEME/MEME/Artist/ArtistPortfolio/ArtistPortfolioManageView/ArtistPortfolioManageViewController.xib
  MEME/MEME/Artist/ArtistReservation/ArtistReservationStatusTableViewCell/ArtistReservationStatusTableViewCell.xib
  MEME/MEME/Artist/ArtistReservation/SingleArtistReservationManageView/SingleArtistReservationManageViewController.swift
Labels: refactoring
